### ISSUE TITLE
Use access control lists for user rights management

### ISSUE THREAD

**Issue by jreicht** [eduboard/backend#1]
User rights management is needed for making some content only visible/editable for a certain group of users or even for certain users. Hence, it might be useful to control these rights via per-person and per-group access control lists (ACLs).

**Comment by ldb** [comment]
Ideally ACLs would be part of the authentication process. This would require us to switch all HTTP handling to use `context`s instead of `responseWriter`s and `request`s. This way, the authentication middleware could fetch the users Control Lists on every request and pass them on to following middlewares and handlers in the request context.

**Comment by ldb** [comment]
In the same breath, `/me` endpoint could be refactored to use context instead of manipulating request headers as it does right now.

**Comment by ldb** [comment]
Since we decided to move to a usertype kind of authorisation model, this is no longer needed. Closing.
